service:
  name: template-kaskadi-api
package:
  individually: true
  exclude:
    - '**/**'
plugins:
  - serverless-aws-documentation
  - serverless-offline
custom:
  # this field defines the hostname and root that will be used to build the API base URL in the documentation
  kaskadi-docs:
    hostname: api.template.com # this defaults to API_DOMAIN if nothing is specified
    root: logical-unit
  documentation:
    api:
      info:
        version: 1.0.0
        title: ${self:service.name}
        description: Template API
provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  apiName: ${self:service.name}
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket
  stackTags:
    app: your-app-name
  tags:
    app: your-app-name
    service: ${self:service.name}
    logical-unit: api-logical-unit
    type: s3, sns, etc.
functions:
  HelloWorld: ${file(./lambdas/hello-world/serverless.yml)}
# customize as needed if you want to use layers for your API
layers:
  ApiLayer: ${file(./layer/serverless.yml)}